#pragma once
// GENERATED by scripts/gen_cgb_palettes.py from SameBoy's cgb_boot.asm.
// Do not hand-edit; regenerate. See the script for the source and licence.
//
// The Game Boy Color boot ROM's compatibility palettes for DMG cartridges.
// Colours are native RGB565, converted from the ROM's BGR555.

#include <stdint.h>

#define CGB_PAL_CHECKSUM_COUNT 94
#define CGB_PAL_FIRST_DUPLICATE 65
#define CGB_PAL_COMBO_COUNT 51
#define CGB_PAL_COLOUR_COUNT 120

/* Sum of the 16 title bytes, mod 256. The tail from
   CGB_PAL_FIRST_DUPLICATE on collides and needs the 4th letter too. */
static const uint8_t cgb_pal_checksums[CGB_PAL_CHECKSUM_COUNT] = {
    0x00, 0x88, 0x16, 0x36, 0xD1, 0xDB, 0xF2, 0x3C, 0x8C, 0x92, 0x3D, 0x5C,
    0x58, 0xC9, 0x3E, 0x70, 0x1D, 0x59, 0x69, 0x19, 0x35, 0xA8, 0x14, 0xAA,
    0x75, 0x95, 0x99, 0x34, 0x6F, 0x15, 0xFF, 0x97, 0x4B, 0x90, 0x17, 0x10,
    0x39, 0xF7, 0xF6, 0xA2, 0x49, 0x4E, 0x43, 0x68, 0xE0, 0x8B, 0xF0, 0xCE,
    0x0C, 0x29, 0xE8, 0xB7, 0x86, 0x9A, 0x52, 0x01, 0x9D, 0x71, 0x9C, 0xBD,
    0x5D, 0x6D, 0x67, 0x3F, 0x6B, 0xB3, 0x46, 0x28, 0xA5, 0xC6, 0xD3, 0x27,
    0x61, 0x18, 0x66, 0x6A, 0xBF, 0x0D, 0xF4, 0xB3, 0x46, 0x28, 0xA5, 0xC6,
    0xD3, 0x27, 0x61, 0x18, 0x66, 0x6A, 0xBF, 0x0D, 0xF4, 0xB3,
};

/* Combination id per checksum, 1:1 with the array above. */
static const uint8_t cgb_pal_combo_of[CGB_PAL_CHECKSUM_COUNT] = {
      0,   4,   5,  35,  34,   3,  31,  15,  10,   5,  19,  36,
      7,  37,  30,  44,  21,  32,  31,  20,   5,  33,  13,  14,
      5,  29,   5,  18,   9,   3,   2,  26,  25,  25,  41,  42,
     26,  45,  42,  45,  36,  38,  26,  42,  30,  41,  34,  34,
      5,  42,   6,   5,  33,  25,  42,  42,  40,   2,  16,  25,
     42,  42,   5,   0,  39,  36,  22,  25,   6,  32,  12,  36,
     11,  39,  18,  39,  24,  31,  50,  17,  46,   6,  27,   0,
     47,  41,  41,   0,   0,  19,  34,  23,  18,  29,
};

/* The title's 4th character, for the colliding tail only. */
static const char cgb_pal_fourth[] = "BEFAARBEKEK R-URAR INAILICE R";

/* OBJ0, OBJ1, BG as BYTE offsets into cgb_pal_colours — three of them
   are misaligned on purpose and straddle two palettes. */
static const uint8_t cgb_pal_combos[CGB_PAL_COMBO_COUNT][3] = {
    {  32,  32, 232 },  /*  0 */
    { 144, 144, 144 },  /*  1 */
    { 160, 160, 160 },  /*  2 */
    { 192, 192, 192 },  /*  3 */
    {  72,  72,  72 },  /*  4 */
    {   0,   0,   0 },  /*  5 */
    { 216, 216, 216 },  /*  6 */
    {  40,  40,  40 },  /*  7 */
    {  96,  96,  96 },  /*  8 */
    { 208, 208, 208 },  /*  9 */
    { 128,  64,  64 },  /* 10 */
    {  32, 224, 224 },  /* 11 */
    {  32,  16,  16 },  /* 12 */
    {  24,  32,  32 },  /* 13 */
    {  32, 232, 232 },  /* 14 */
    { 224,  32, 224 },  /* 15 */
    {  16, 136,  16 },  /* 16 */
    { 128, 128,  64 },  /* 17 */
    {  32,  32,  56 },  /* 18 */
    {  32,  32, 144 },  /* 19 */
    {  32,  32, 160 },  /* 20 */
    { 152, 152,  72 },  /* 21 */
    {  30,  30,  88 },  /* 22 */
    { 136, 136,  16 },  /* 23 */
    {  32,  32,  16 },  /* 24 */
    {  32,  32,  24 },  /* 25 */
    { 224, 224,   0 },  /* 26 */
    {  24,  24,   0 },  /* 27 */
    {   0,   0,   8 },  /* 28 */
    { 144, 176, 144 },  /* 29 */
    { 160, 176, 160 },  /* 30 */
    { 192, 176, 192 },  /* 31 */
    { 128, 176,  64 },  /* 32 */
    { 136,  32, 104 },  /* 33 */
    { 222,   0, 112 },  /* 34 */
    { 222,  32, 120 },  /* 35 */
    { 152, 182,  72 },  /* 36 */
    { 128, 224,  80 },  /* 37 */
    {  32, 184, 224 },  /* 38 */
    { 136, 176,  16 },  /* 39 */
    {  32,   0,  16 },  /* 40 */
    {  32, 224,  24 },  /* 41 */
    { 224,  24,   0 },  /* 42 */
    {  24, 224,  32 },  /* 43 */
    { 168, 224,  32 },  /* 44 */
    {  24, 224,   0 },  /* 45 */
    { 200,  24, 224 },  /* 46 */
    {   0, 224,  64 },  /* 47 */
    {  32,  24, 224 },  /* 48 */
    { 224,  24,  48 },  /* 49 */
    {  32, 224, 232 },  /* 50 */
};

static const uint16_t cgb_pal_colours[CGB_PAL_COLOUR_COUNT] = {
    0xFFFF, 0xFD6C, 0x8180, 0x0000,
    0xFF38, 0xCCF0, 0x8345, 0x5981,
    0xFFFF, 0x8C7B, 0x5291, 0x0000,
    0xFFFF, 0x7FE6, 0x0420, 0x0000,
    0xFFFF, 0xFC30, 0x91C7, 0x0000,
    0xFFFF, 0xA534, 0x528A, 0x0000,
    0xFFFF, 0xFFE0, 0x7A40, 0x0000,
    0xFFFF, 0x7FE0, 0xB380, 0x0000,
    0xFFFF, 0xAD70, 0x438F, 0x0000,
    0xA4FF, 0xFFE0, 0x0300, 0x0000,
    0xFFF9, 0x677D, 0x9C26, 0x5ACB,
    0xB5BF, 0xFFF2, 0xAAC8, 0x0000,
    0xFFF4, 0xFCB2, 0x94BF, 0x0000,
    0xFFF3, 0x95BF, 0x64AE, 0x01C7,
    0x6FE0, 0xFFFF, 0xFA89, 0x0000,
    0x56E0, 0xFC20, 0xFFE0, 0xFFFF,
    0xFFFF, 0xFB80, 0x9200, 0x0000,
    0xFE28, 0xFEA0, 0x91C0, 0x4800,
    0xFFFF, 0x57E0, 0xFA00, 0x0000,
    0xFB0A, 0xD000, 0x6000, 0x0000,
    0xFFFF, 0xFCE0, 0xF800, 0x0000,
    0xFFFF, 0x07E0, 0x3420, 0x0240,
    0xFFFF, 0x5DFF, 0xF800, 0x001F,
    0xFFFF, 0xFFEF, 0x043F, 0xF800,
    0xFFFF, 0xFFE0, 0xF800, 0x0000,
    0xFFE0, 0xF800, 0x6000, 0x0000,
    0xFFFF, 0xFE60, 0x9B00, 0x0000,
    0x0000, 0x0430, 0xFEE0, 0xFFFF,
    0xFFFF, 0x653F, 0x001F, 0x0000,
    0xFFFF, 0x7FE6, 0x0318, 0x0000,
};

