"""The committed library fixture must not drift from games.json.

test/fixtures/catalog_library.txt is generated by
`tools/image_sd.py --catalog-only`, and test/test_catalog/ indexes it with the
firmware's own reader. If games.json changes without the fixture being
regenerated, the firmware would be tested against a catalog no card carries —
so this test fails until they agree again.
"""

import gamesdb


def library_fixture(repo_root):
    return repo_root / "test" / "fixtures" / "catalog_library.txt"


def test_the_fixture_is_the_emitted_catalog_byte_for_byte(repo_root):
    games = gamesdb.load_games(repo_root / "games.json")
    emitted = gamesdb.emit_catalog(games).encode("ascii")

    assert library_fixture(repo_root).read_bytes() == emitted, (
        "test/fixtures/catalog_library.txt is stale; regenerate it with "
        "python tools/image_sd.py --catalog-only test/fixtures/catalog_library.txt"
    )


def test_the_non_empty_line_count_equals_the_entry_count(repo_root):
    games = gamesdb.load_games(repo_root / "games.json")
    text = library_fixture(repo_root).read_text(encoding="ascii")
    lines = [line for line in text.split("\n") if line != ""]

    assert len(lines) == len(games)


def test_the_fixture_is_within_the_readers_limits(repo_root):
    text = library_fixture(repo_root).read_text(encoding="ascii")
    lines = [line for line in text.split("\n") if line != ""]

    assert len(lines) <= gamesdb.CATALOG_MAX
    for line in lines:
        assert line.count("\t") >= 3
        assert gamesdb.byte_len(line) <= gamesdb.CATALOG_LINE_MAX - 1


def test_the_fixture_carries_no_carriage_return_and_ends_in_one_newline(repo_root):
    text = library_fixture(repo_root).read_text(encoding="ascii")

    assert "\r" not in text
    assert text.endswith("\n")
    assert not text.endswith("\n\n")


def test_the_fixture_round_trips_through_the_mirror_parser(repo_root):
    games = gamesdb.load_games(repo_root / "games.json")
    parsed = gamesdb.parse_catalog(
        library_fixture(repo_root).read_text(encoding="ascii")
    )

    assert [entry["filename"] for entry in parsed] == [
        game["filename"] for game in games
    ]
    assert [entry["title"] for entry in parsed] == [game["title"] for game in games]


def test_the_hand_fixture_is_untouched(repo_root):
    """The six-line edge-case fixture is a separate file and stays as it is."""
    hand = (repo_root / "test" / "fixtures" / "catalog.txt").read_bytes()

    assert len([line for line in hand.split(b"\n") if line != b""]) == 6
    assert hand.startswith(b"Tetris.gb\tTetris\tstarter\t")
    assert hand.endswith(b"Alleyway.gb\tAlleyway\t\t\n")
