"""One-shot generator for the tables in lib/gbcore/cart/cgb_palette_table.h.

These are the Game Boy Color boot ROM's own compatibility palettes: the data
the CGB uses to colourise an original DMG cartridge, so that Pokemon Red comes
out red and Zelda green without anyone choosing anything.

Source
------
SameBoy's CGB bootstrap, BootROMs/cgb_boot.asm — a from-scratch reimplementation
by Lior Halphon carrying the original tables, licensed Expat/MIT, which this
firmware's GPL-2.0-or-later accepts. Pin the commit when regenerating:

    curl -sL -o cgb_boot.asm \\
      https://raw.githubusercontent.com/LIJI32/SameBoy/<commit>/BootROMs/cgb_boot.asm
    python3 scripts/gen_cgb_palettes.py cgb_boot.asm \\
      > lib/gbcore/cart/cgb_palette_table.h

The four SameBoy-exclusive combinations and the two SameBoy-exclusive palettes
are excluded: they sit behind boot-time button combos this firmware has no
equivalent of, and they are not Nintendo's.

Shape
-----
    TitleChecksums[94]        sum of the 16 title bytes, mod 256
    PalettePerChecksum[94]    combination id for each, 1:1 with the above
    Dups4thLetter[29]         disambiguates the last 29, which collide
    Combinations[51][3]       OBJ0, OBJ1, BG as byte offsets into Palettes
    Palettes[120]             30 x 4 colours, flat

The combination entries are BYTE offsets, not palette indices, on purpose:
three of them are deliberately misaligned and read a four-colour window that
straddles two palettes. Dividing them down to a palette index would quietly
lose that.

Colour conversion is BGR555 -> RGB565 with the green bit replicated
(g6 = g5 << 1 | g5 >> 4), no gamut correction: the CGB's colours were picked
for its own washed-out reflective LCD, and a correction curve is a separate
judgement from reproducing the table.

Run from the project root. Prints the header to stdout; the output is
committed, so this is a record of the derivation and a way to regenerate it,
not a build step.
"""

import re
import sys

SAMEBOY_EXCLUSIVE = '; SameBoy "Exclusives"'


def between(text, start, end):
    a = text.index(start) + len(start)
    return text[a:text.index(end, a)]


def nintendo_only(block):
    return block.split(SAMEBOY_EXCLUSIVE)[0]


def parse(asm):
    checksums_block = between(asm, "TitleChecksums:", "ChecksumsEnd:")
    split = checksums_block.index("FirstChecksumWithDuplicate:")
    unique = re.findall(r"db \$([0-9A-Fa-f]{2})", checksums_block[:split])
    duplicated = re.findall(r"db \$([0-9A-Fa-f]{2})", checksums_block[split:])

    per_checksum = [
        int(n) & 0x7F  # bit 7 asks for the DMG boot tilemap; not our concern
        for n in re.findall(
            r"palette_index\s+(\d+)",
            between(asm, "PalettePerChecksum:", "Dups4thLetterArray:"),
        )
    ]

    fourth = re.search(
        r'db "([^"]*)"', between(asm, "Dups4thLetterArray:", "PaletteCombinations:")
    ).group(1)

    combos = []
    for raw, args in re.findall(
        r"(raw_)?palette_comb\s+([-0-9*, ]+)",
        nintendo_only(between(asm, "PaletteCombinations:", "Palettes:")),
    ):
        scale = 2 if raw else 8
        combos.append(tuple(eval(a) * scale for a in args.split(",")))

    colours = []
    for line in nintendo_only(asm[asm.index("\nPalettes:"):]).splitlines():
        m = re.match(r"\s*dw\s+(.+?)\s*(?:;.*)?$", line)
        if m:
            colours += [int(v.strip().lstrip("$"), 16) for v in m.group(1).split(",")]

    return unique, duplicated, per_checksum, fourth, combos, colours


def to_rgb565(bgr555):
    r = bgr555 & 0x1F
    g = (bgr555 >> 5) & 0x1F
    b = (bgr555 >> 10) & 0x1F
    return (r << 11) | ((g << 1 | g >> 4) << 5) | b


def rows(values, per_row, fmt):
    for i in range(0, len(values), per_row):
        yield "    " + " ".join(fmt(v) + "," for v in values[i:i + per_row])


def main(path):
    unique, duplicated, per_checksum, fourth, combos, colours = parse(open(path).read())
    checksums = unique + duplicated

    # The parse is worth nothing if the arrays do not line up, and the failure
    # would be a wrong palette rather than a crash.
    assert len(checksums) == len(per_checksum), (len(checksums), len(per_checksum))
    assert len(fourth) == len(duplicated), (len(fourth), len(duplicated))
    assert len(colours) == 4 * (max(max(c) for c in combos) // 8 + 1), len(colours)
    # Two spot checks against the asm's own comments, so a silently reordered
    # table cannot pass: TETRIS is unique, POKEMON BLUE needs the 4th letter.
    assert checksums[: len(unique)][5] == "DB", checksums[5]
    assert sum(b"POKEMON BLUE") % 256 == 0x61

    out = [
        "#pragma once",
        "// GENERATED by scripts/gen_cgb_palettes.py from SameBoy's cgb_boot.asm.",
        "// Do not hand-edit; regenerate. See the script for the source and licence.",
        "//",
        "// The Game Boy Color boot ROM's compatibility palettes for DMG cartridges.",
        "// Colours are native RGB565, converted from the ROM's BGR555.",
        "",
        "#include <stdint.h>",
        "",
        "#define CGB_PAL_CHECKSUM_COUNT %d" % len(checksums),
        "#define CGB_PAL_FIRST_DUPLICATE %d" % len(unique),
        "#define CGB_PAL_COMBO_COUNT %d" % len(combos),
        "#define CGB_PAL_COLOUR_COUNT %d" % len(colours),
        "",
        "/* Sum of the 16 title bytes, mod 256. The tail from",
        "   CGB_PAL_FIRST_DUPLICATE on collides and needs the 4th letter too. */",
        "static const uint8_t cgb_pal_checksums[CGB_PAL_CHECKSUM_COUNT] = {",
    ]
    out += rows(checksums, 12, lambda v: "0x" + v.upper())
    out += [
        "};",
        "",
        "/* Combination id per checksum, 1:1 with the array above. */",
        "static const uint8_t cgb_pal_combo_of[CGB_PAL_CHECKSUM_COUNT] = {",
    ]
    out += rows(per_checksum, 12, lambda v: "%3d" % v)
    out += [
        "};",
        "",
        "/* The title's 4th character, for the colliding tail only. */",
        'static const char cgb_pal_fourth[] = "%s";' % fourth,
        "",
        "/* OBJ0, OBJ1, BG as BYTE offsets into cgb_pal_colours — three of them",
        "   are misaligned on purpose and straddle two palettes. */",
        "static const uint8_t cgb_pal_combos[CGB_PAL_COMBO_COUNT][3] = {",
    ]
    out += [
        "    { %3d, %3d, %3d },  /* %2d */" % (c[0], c[1], c[2], i)
        for i, c in enumerate(combos)
    ]
    out += [
        "};",
        "",
        "static const uint16_t cgb_pal_colours[CGB_PAL_COLOUR_COUNT] = {",
    ]
    out += rows([to_rgb565(c) for c in colours], 4, lambda v: "0x%04X" % v)
    out += ["};", ""]
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "cgb_boot.asm")
