#include <unity.h>

#include <string.h>

#include "render/palette.h"
#include "cart/cgb_palette_table.h"

/*
 * Palette suite.
 *
 * Two pins. Pocket Gray's BG ramp is the fork's original, carried over, and
 * entries 2-13 are the Game Boy Color boot ROM's button-combo palettes, so
 * every one of their rows must equal the CGB table's own colours for that
 * combination. The derived OBJ ramps of entries 0 and 1 are deliberately NOT
 * pinned as values — they are generated by scripts/gen_palettes.py, and
 * pinning them would turn every regeneration into a test edit. Their contract
 * is asserted as properties instead: fully populated, distinct from BG, and
 * ordered light to dark like the ramp the Game Boy assumes.
 */

/* Ramp index within a palette, from the raw pixel byte's bits 5-4. */
#define RAMP_OBJ0 0
#define RAMP_OBJ1 1
#define RAMP_BG 2

#define LUT_ENTRY(ramp, shade) (((ramp) << 4) | (shade))

/* The first entry that is a CGB button-combo palette; the ones before it have
 * derived OBJ ramps. */
#define FIRST_CGB 2

/* The one palette whose ramps run dark to light: CGB Right + B. */
#define REVERSE_PALETTE 4

static const uint16_t pocket_gray_bg[4] = { 0xFFFF, 0xB596, 0x6B4D, 0x0000 };

/* CGB combination id for entries FIRST_CGB.., in menu order: each direction,
 * then with A, then with B. */
static const uint8_t cgb_combo_ids[PALETTE_COUNT - FIRST_CGB] = {
    1, 0, 6,     /* Right, Right + A, Right + B */
    48, 40, 7,   /* Left */
    5, 43, 28,   /* Up */
    8, 3, 49,    /* Down */
};

static const char* expected_names[PALETTE_COUNT] = {
    "DMG Green", "Pocket Gray",
    "Green", "Dark Green", "Reverse",
    "Blue", "Dark Blue", "Grayscale",
    "Brown", "Red", "Dark Brown",
    "Pastel", "Orange", "Yellow",
};

#define UNSET 0xDEADu

static uint16_t lut[PALETTE_LUT_SIZE];

void setUp(void)
{
    unsigned i;
    for (i = 0; i < PALETTE_LUT_SIZE; i++) {
        lut[i] = UNSET;
    }
}

void tearDown(void)
{
}

/* Integer luma over the fields expanded to 8 bits, weights 2:5:1. Enough to
 * order four shades; no floating point, no colour-space library. */
static unsigned luma(uint16_t c)
{
    unsigned r = (((c >> 11) & 31u) * 255u + 15u) / 31u;
    unsigned g = (((c >> 5) & 63u) * 255u + 31u) / 63u;
    unsigned b = ((c & 31u) * 255u + 15u) / 31u;
    return 2u * r + 5u * g + b;
}

static void test_there_are_fourteen_palettes(void)
{
    TEST_ASSERT_EQUAL_INT(14, PALETTE_COUNT);
}

static void test_pocket_gray_bg_is_the_forks_original(void)
{
    unsigned c;

    palette_build_lut(1, lut);
    for (c = 0; c < 4u; c++) {
        TEST_ASSERT_EQUAL_HEX16(pocket_gray_bg[c], lut[LUT_ENTRY(RAMP_BG, c)]);
    }
}

static void test_cgb_entries_are_the_boot_roms_combo_palettes(void)
{
    unsigned p;
    unsigned ramp;
    unsigned c;

    for (p = FIRST_CGB; p < PALETTE_COUNT; p++) {
        const uint8_t* combo = cgb_pal_combos[cgb_combo_ids[p - FIRST_CGB]];
        palette_build_lut((uint8_t)p, lut);
        for (ramp = 0; ramp <= RAMP_BG; ramp++) {
            /* Byte offsets, as cart/cgb_palette.c resolves them. */
            unsigned first = combo[ramp] / 2u;
            for (c = 0; c < 4u; c++) {
                TEST_ASSERT_EQUAL_HEX16_MESSAGE(
                    cgb_pal_colours[first + c], lut[LUT_ENTRY(ramp, c)],
                    "a CGB entry differs from the boot ROM's own colours");
            }
        }
    }
}

static void test_every_lut_entry_is_populated(void)
{
    unsigned p;
    unsigned i;

    for (p = 0; p < PALETTE_COUNT; p++) {
        setUp();
        palette_build_lut((uint8_t)p, lut);
        for (i = 0; i < PALETTE_LUT_SIZE; i++) {
            TEST_ASSERT_NOT_EQUAL_MESSAGE(UNSET, lut[i],
                "a raw pixel byte would index an undefined colour");
        }
    }
}

static void test_ramp_bits_above_bg_fold_onto_bg(void)
{
    unsigned p;
    unsigned c;

    /* A real pixel byte tops out at 0x23, so ramp index 3 is unreachable —
     * but it must still resolve, which is what removes the & 3 from the
     * inner loop. */
    for (p = 0; p < PALETTE_COUNT; p++) {
        palette_build_lut((uint8_t)p, lut);
        for (c = 0; c < 4u; c++) {
            TEST_ASSERT_EQUAL_HEX16(lut[LUT_ENTRY(RAMP_BG, c)],
                                    lut[LUT_ENTRY(3, c)]);
        }
    }
}

static void test_lut_ramps_are_distinct_from_each_other(void)
{
    unsigned p;

    /* The point of the 12-colour path: a derived OBJ0 and OBJ1 are not just
     * copies of BG. Compared as whole ramps, so a palette whose white or black
     * is a shared fixed point still counts. The CGB entries are left out:
     * several use one ramp for all three rows, and that is Nintendo's choice. */
    for (p = 0; p < FIRST_CGB; p++) {
        palette_build_lut((uint8_t)p, lut);
        TEST_ASSERT_NOT_EQUAL(0, memcmp(&lut[LUT_ENTRY(RAMP_OBJ0, 0)],
                                       &lut[LUT_ENTRY(RAMP_BG, 0)],
                                       4 * sizeof(uint16_t)));
        TEST_ASSERT_NOT_EQUAL(0, memcmp(&lut[LUT_ENTRY(RAMP_OBJ1, 0)],
                                       &lut[LUT_ENTRY(RAMP_BG, 0)],
                                       4 * sizeof(uint16_t)));
        TEST_ASSERT_NOT_EQUAL(0, memcmp(&lut[LUT_ENTRY(RAMP_OBJ0, 0)],
                                       &lut[LUT_ENTRY(RAMP_OBJ1, 0)],
                                       4 * sizeof(uint16_t)));
    }
}

static void test_every_ramp_runs_light_to_dark(void)
{
    unsigned p;
    unsigned ramp;
    unsigned c;

    for (p = 0; p < PALETTE_COUNT; p++) {
        palette_build_lut((uint8_t)p, lut);
        for (ramp = 0; ramp <= RAMP_BG; ramp++) {
            for (c = 0; c + 1u < 4u; c++) {
                unsigned a = luma(lut[LUT_ENTRY(ramp, c)]);
                unsigned b = luma(lut[LUT_ENTRY(ramp, c + 1u)]);
                if (p == REVERSE_PALETTE) {
                    TEST_ASSERT_TRUE_MESSAGE(a <= b,
                        "Reverse's ramps must run dark to light");
                } else {
                    TEST_ASSERT_TRUE_MESSAGE(a >= b,
                        "a ramp is not ordered light to dark — fix the "
                        "generator, not this assertion");
                }
            }
        }
    }
}

static void test_palette_names_match_the_list(void)
{
    unsigned p;

    for (p = 0; p < PALETTE_COUNT; p++) {
        const char* name = palette_name((uint8_t)p);
        TEST_ASSERT_NOT_NULL(name);
        TEST_ASSERT_TRUE(name[0] != '\0');
        TEST_ASSERT_EQUAL_STRING(expected_names[p], name);
    }
}

static void test_palette_name_reports_unknown_out_of_range(void)
{
    TEST_ASSERT_EQUAL_STRING("?", palette_name(PALETTE_COUNT));
    TEST_ASSERT_EQUAL_STRING("?", palette_name(255));
}

static void test_out_of_range_and_null_leave_the_lut_alone(void)
{
    unsigned i;

    /* The header's documented choice: a bad index writes nothing, so the
     * caller keeps the palette it already had. */
    palette_build_lut(1, lut);
    palette_build_lut(PALETTE_COUNT, lut);
    for (i = 0; i < 4u; i++) {
        TEST_ASSERT_EQUAL_HEX16(pocket_gray_bg[i], lut[LUT_ENTRY(RAMP_BG, i)]);
    }
    palette_build_lut(255, lut);
    for (i = 0; i < 4u; i++) {
        TEST_ASSERT_EQUAL_HEX16(pocket_gray_bg[i], lut[LUT_ENTRY(RAMP_BG, i)]);
    }
    palette_build_lut(0, NULL); /* must not crash */
}

int main(void)
{
    UNITY_BEGIN();
    RUN_TEST(test_there_are_fourteen_palettes);
    RUN_TEST(test_pocket_gray_bg_is_the_forks_original);
    RUN_TEST(test_cgb_entries_are_the_boot_roms_combo_palettes);
    RUN_TEST(test_every_lut_entry_is_populated);
    RUN_TEST(test_ramp_bits_above_bg_fold_onto_bg);
    RUN_TEST(test_lut_ramps_are_distinct_from_each_other);
    RUN_TEST(test_every_ramp_runs_light_to_dark);
    RUN_TEST(test_palette_names_match_the_list);
    RUN_TEST(test_palette_name_reports_unknown_out_of_range);
    RUN_TEST(test_out_of_range_and_null_leave_the_lut_alone);
    return UNITY_END();
}
