#include <unity.h>

#include <string.h>

#include "render/palette.h"

/*
 * Palette suite.
 *
 * The BG table below is the regression pin: it is the fork's original
 * pre-colourization 20 x 4 palette table, transcribed from
 * src/emulator_bridge.cpp, and every palette's BG ramp must still equal it
 * exactly. The derived OBJ ramps are deliberately NOT pinned as values — they
 * are generated by scripts/gen_palettes.py, and pinning them would turn every
 * regeneration into a test edit. Their contract is asserted as properties
 * instead: fully populated, and ordered light to dark like the ramp the Game
 * Boy assumes.
 */

/* Ramp index within a palette, from the raw pixel byte's bits 5-4. */
#define RAMP_OBJ0 0
#define RAMP_OBJ1 1
#define RAMP_BG 2

#define LUT_ENTRY(ramp, shade) (((ramp) << 4) | (shade))

/* The one palette whose ramp runs dark to light. */
#define INVERTED_PALETTE 18

static const uint16_t expected_bg[PALETTE_COUNT][4] = {
    { 0x9FE5, 0x4F64, 0x2542, 0x0261 }, /*  0 Classic Green */
    { 0xFFFF, 0xAD55, 0x52AA, 0x0000 }, /*  1 Original DMG  */
    { 0xFFFF, 0xB596, 0x6B4D, 0x0000 }, /*  2 Pocket Gray   */
    { 0xFFDF, 0xD68F, 0x7A4B, 0x1082 }, /*  3 Warm Sepia    */
    { 0xBF5F, 0x6CDF, 0x339F, 0x0019 }, /*  4 Cool Blue     */
    { 0xFFF0, 0xFC00, 0x8800, 0x2000 }, /*  5 Autumn        */
    { 0xE71C, 0x9CD3, 0x4228, 0x0000 }, /*  6 Grayscale     */
    { 0xFFFF, 0xFE20, 0xC800, 0x4000 }, /*  7 Lava          */
    { 0xAFFF, 0x5F5F, 0x2D1F, 0x0019 }, /*  8 Ocean         */
    { 0xFFF0, 0xBDE0, 0x5AE0, 0x0120 }, /*  9 Forest        */
    { 0xFFFF, 0xFD20, 0xAB00, 0x4000 }, /* 10 Sunset        */
    { 0xFFDF, 0xF71C, 0xAA13, 0x3808 }, /* 11 Cherry        */
    { 0xCFFF, 0x867F, 0x433F, 0x0019 }, /* 12 Ice           */
    { 0xFFB6, 0xD52A, 0x8A08, 0x3000 }, /* 13 Chocolate     */
    { 0xFFFF, 0xBF5F, 0x5F1F, 0x0019 }, /* 14 Mint          */
    { 0xFFF8, 0xFCC0, 0xC880, 0x6000 }, /* 15 Peach         */
    { 0xEF3C, 0x867F, 0x4179, 0x0000 }, /* 16 Lavender      */
    { 0xFFFF, 0x07FF, 0x001F, 0x0000 }, /* 17 Neon          */
    { 0x0000, 0x4228, 0xAD55, 0xFFFF }, /* 18 Inverted      */
    { 0xFE60, 0xAB00, 0x5000, 0x0000 }, /* 19 Gold          */
};

static const char* expected_names[PALETTE_COUNT] = {
    "Classic Green", "Original DMG", "Pocket Gray", "Warm Sepia", "Cool Blue",
    "Autumn", "Grayscale", "Lava", "Ocean", "Forest",
    "Sunset", "Cherry", "Ice", "Chocolate", "Mint",
    "Peach", "Lavender", "Neon", "Inverted", "Gold",
};

#define UNSET 0xDEADu

static uint16_t lut[PALETTE_LUT_SIZE];

void setUp(void)
{
    unsigned i;
    for (i = 0; i < PALETTE_LUT_SIZE; i++) {
        lut[i] = UNSET;
    }
}

void tearDown(void)
{
}

/* Integer luma over the fields expanded to 8 bits, weights 2:5:1. Enough to
 * order four shades; no floating point, no colour-space library. */
static unsigned luma(uint16_t c)
{
    unsigned r = (((c >> 11) & 31u) * 255u + 15u) / 31u;
    unsigned g = (((c >> 5) & 63u) * 255u + 31u) / 63u;
    unsigned b = ((c & 31u) * 255u + 15u) / 31u;
    return 2u * r + 5u * g + b;
}

static void test_bg_ramps_are_the_forks_originals_verbatim(void)
{
    unsigned p;
    unsigned c;

    for (p = 0; p < PALETTE_COUNT; p++) {
        palette_build_lut((uint8_t)p, lut);
        for (c = 0; c < 4u; c++) {
            TEST_ASSERT_EQUAL_HEX16_MESSAGE(
                expected_bg[p][c], lut[LUT_ENTRY(RAMP_BG, c)],
                "a palette's BG ramp changed — BG ramps are kept verbatim, so "
                "this is a regression unless the decision that pins them was "
                "superseded");
        }
    }
}

static void test_every_lut_entry_is_populated(void)
{
    unsigned p;
    unsigned i;

    for (p = 0; p < PALETTE_COUNT; p++) {
        setUp();
        palette_build_lut((uint8_t)p, lut);
        for (i = 0; i < PALETTE_LUT_SIZE; i++) {
            TEST_ASSERT_NOT_EQUAL_MESSAGE(UNSET, lut[i],
                "a raw pixel byte would index an undefined colour");
        }
    }
}

static void test_ramp_bits_above_bg_fold_onto_bg(void)
{
    unsigned p;
    unsigned c;

    /* A real pixel byte tops out at 0x23, so ramp index 3 is unreachable —
     * but it must still resolve, which is what removes the & 3 from the
     * inner loop. */
    for (p = 0; p < PALETTE_COUNT; p++) {
        palette_build_lut((uint8_t)p, lut);
        for (c = 0; c < 4u; c++) {
            TEST_ASSERT_EQUAL_HEX16(lut[LUT_ENTRY(RAMP_BG, c)],
                                    lut[LUT_ENTRY(3, c)]);
        }
    }
}

static void test_lut_ramps_are_distinct_from_each_other(void)
{
    unsigned p;

    /* The point of the 12-colour path: OBJ0 and OBJ1 are not just copies of
     * BG. Compared as whole ramps, so a palette whose white or black is a
     * shared fixed point still counts. */
    for (p = 0; p < PALETTE_COUNT; p++) {
        palette_build_lut((uint8_t)p, lut);
        TEST_ASSERT_NOT_EQUAL(0, memcmp(&lut[LUT_ENTRY(RAMP_OBJ0, 0)],
                                       &lut[LUT_ENTRY(RAMP_BG, 0)],
                                       4 * sizeof(uint16_t)));
        TEST_ASSERT_NOT_EQUAL(0, memcmp(&lut[LUT_ENTRY(RAMP_OBJ1, 0)],
                                       &lut[LUT_ENTRY(RAMP_BG, 0)],
                                       4 * sizeof(uint16_t)));
        TEST_ASSERT_NOT_EQUAL(0, memcmp(&lut[LUT_ENTRY(RAMP_OBJ0, 0)],
                                       &lut[LUT_ENTRY(RAMP_OBJ1, 0)],
                                       4 * sizeof(uint16_t)));
    }
}

static void test_every_ramp_runs_light_to_dark(void)
{
    unsigned p;
    unsigned ramp;
    unsigned c;

    for (p = 0; p < PALETTE_COUNT; p++) {
        palette_build_lut((uint8_t)p, lut);
        for (ramp = 0; ramp <= RAMP_BG; ramp++) {
            for (c = 0; c + 1u < 4u; c++) {
                unsigned a = luma(lut[LUT_ENTRY(ramp, c)]);
                unsigned b = luma(lut[LUT_ENTRY(ramp, c + 1u)]);
                if (p == INVERTED_PALETTE) {
                    TEST_ASSERT_TRUE_MESSAGE(a <= b,
                        "Inverted's ramps must run dark to light");
                } else {
                    TEST_ASSERT_TRUE_MESSAGE(a >= b,
                        "a ramp is not ordered light to dark — fix the "
                        "generator, not this assertion");
                }
            }
        }
    }
}

static void test_palette_names_match_the_forks_list(void)
{
    unsigned p;

    for (p = 0; p < PALETTE_COUNT; p++) {
        const char* name = palette_name((uint8_t)p);
        TEST_ASSERT_NOT_NULL(name);
        TEST_ASSERT_TRUE(name[0] != '\0');
        TEST_ASSERT_EQUAL_STRING(expected_names[p], name);
    }
}

static void test_palette_name_reports_unknown_out_of_range(void)
{
    TEST_ASSERT_EQUAL_STRING("?", palette_name(PALETTE_COUNT));
    TEST_ASSERT_EQUAL_STRING("?", palette_name(255));
}

static void test_out_of_range_and_null_leave_the_lut_alone(void)
{
    unsigned i;

    /* The header's documented choice: a bad index writes nothing, so the
     * caller keeps the palette it already had. */
    palette_build_lut(0, lut);
    palette_build_lut(PALETTE_COUNT, lut);
    for (i = 0; i < 4u; i++) {
        TEST_ASSERT_EQUAL_HEX16(expected_bg[0][i], lut[LUT_ENTRY(RAMP_BG, i)]);
    }
    palette_build_lut(255, lut);
    for (i = 0; i < 4u; i++) {
        TEST_ASSERT_EQUAL_HEX16(expected_bg[0][i], lut[LUT_ENTRY(RAMP_BG, i)]);
    }
    palette_build_lut(0, NULL); /* must not crash */
}

int main(void)
{
    UNITY_BEGIN();
    RUN_TEST(test_bg_ramps_are_the_forks_originals_verbatim);
    RUN_TEST(test_every_lut_entry_is_populated);
    RUN_TEST(test_ramp_bits_above_bg_fold_onto_bg);
    RUN_TEST(test_lut_ramps_are_distinct_from_each_other);
    RUN_TEST(test_every_ramp_runs_light_to_dark);
    RUN_TEST(test_palette_names_match_the_forks_list);
    RUN_TEST(test_palette_name_reports_unknown_out_of_range);
    RUN_TEST(test_out_of_range_and_null_leave_the_lut_alone);
    return UNITY_END();
}
