#!/usr/bin/env python3
"""Render a TrueType font into a TFT_eSPI / Adafruit GFX font header.

    python tools/gen_gfx_font.py <font.ttf> <points> <Name> > src/fonts/<Name>.h

TFT_eSPI ships FreeSans at 9, 12, 18 and 24 pt only; the theme wants sizes in
between. This does what Adafruit's fontconvert does — printable ASCII, one bit
a pixel, no anti-aliasing, sized at fontconvert's 141 dpi so a "9 pt" here is
the same pixel size as the library's 9 pt — using Pillow instead of a C build
against FreeType.

It also prints, on stderr, the four numbers canvas.c needs for the font:
the box height (tallest ascent plus deepest descent), the capital height and
the blank rows above the capitals.
"""

import sys

from PIL import Image, ImageDraw, ImageFont

FIRST = 0x20
LAST = 0x7E
DPI = 141


def render(path, points):
    em = points * DPI / 72
    px = round(em)
    font = ImageFont.truetype(path, em)
    ascent, descent = font.getmetrics()
    size = px * 3
    glyphs = []
    bits = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        img = Image.new("1", (size, size), 0)
        draw = ImageDraw.Draw(img)
        draw.fontmode = "1"
        ox, oy = px, 2 * px
        draw.text((ox, oy), ch, font=font, fill=1, anchor="ls")
        box = img.getbbox()
        adv = round(font.getlength(ch))
        if box is None:
            glyphs.append((len(bits) // 8, 0, 0, adv, 0, 0))
            continue
        x0, y0, x1, y1 = box
        start = len(bits)
        for y in range(y0, y1):
            for x in range(x0, x1):
                bits.append(img.getpixel((x, y)) and 1)
        # Each glyph's bits start on a byte, as fontconvert lays them out.
        while len(bits) % 8:
            bits.append(0)
        glyphs.append((start // 8, x1 - x0, y1 - y0, adv, x0 - ox, y0 - oy))
    data = bytes(
        int("".join(str(b) for b in bits[i:i + 8]), 2)
        for i in range(0, len(bits), 8)
    )
    return data, glyphs, ascent + descent


def metrics(glyphs):
    shown = [g for g in glyphs if g[1] and g[2]]
    above = max(-g[5] for g in shown)
    below = max(g[2] + g[5] for g in shown)
    cap = -glyphs[ord("A") - FIRST][5]
    return above + below, cap, above - cap


def main():
    path, points, name = sys.argv[1], float(sys.argv[2]), sys.argv[3]
    data, glyphs, y_adv = render(path, points)
    out = sys.stdout
    out.write(f"// {name}: {path.rsplit('/', 1)[-1]} at {points:g} pt, "
              f"{DPI} dpi, printable ASCII.\n")
    out.write("// Generated by tools/gen_gfx_font.py; do not edit.\n\n")
    out.write("#pragma once\n\n")
    out.write(f"const uint8_t {name}Bitmaps[] PROGMEM = {{\n")
    for i in range(0, len(data), 12):
        row = ", ".join(f"0x{b:02X}" for b in data[i:i + 12])
        out.write(f"  {row},\n")
    out.write("};\n\n")
    out.write(f"const GFXglyph {name}Glyphs[] PROGMEM = {{\n")
    for code, g in zip(range(FIRST, LAST + 1), glyphs):
        out.write(f"  {{ {g[0]:5d}, {g[1]:3d}, {g[2]:3d}, {g[3]:3d}, "
                  f"{g[4]:4d}, {g[5]:4d} }},   // 0x{code:02X}\n")
    out.write("};\n\n")
    out.write(f"const GFXfont {name} PROGMEM = {{\n"
              f"  (uint8_t *){name}Bitmaps,\n"
              f"  (GFXglyph *){name}Glyphs,\n"
              f"  0x{FIRST:02X}, 0x{LAST:02X}, {y_adv} }};\n")
    height, cap, lead = metrics(glyphs)
    sys.stderr.write(f"{name}: height {height} cap {cap} lead {lead} "
                     f"yAdvance {y_adv} bytes {len(data)}\n")


if __name__ == "__main__":
    main()
