"""Image an SD card for the cartridge system, idempotently.

Makes the layout docs/CATALOG_FORMAT.md § SD card layout specifies, from
games.json plus the private ROM and ES-DE media directories:

    /roms/gb/<filename>     the ROM, copied byte for byte
    /art/<stem>.565         cover,   96x96 raw RGB565 little-endian, 18432 bytes
    /shot/<stem>.565        snapshot, same format
    /saves/                 created empty and never otherwise touched
    /catalog.txt            generated by gamesdb.emit_catalog

Ten cards have to be identical, so the tool is idempotent and it prunes: a file
in a managed directory that games.json does not name is removed, because a card
that still carries last week's ROM is not the same card as a fresh one. /saves
is never pruned and never listed — a kid's save is not a stray.

Every write goes to a temp file and is renamed into place, the same shape
sd_save_state() uses on the device, so a card pulled mid-run never holds a half
file. Nothing is written at all until games.json validates.

Images are converted by ffmpeg with the recipe the contract states, never scaled
in Python: the byte order has to match what the display pushes.

    CYD_ROM_DIR=... CYD_MEDIA_DIR=... python tools/image_sd.py --target /run/media/me/GB
    python tools/image_sd.py --catalog-only test/fixtures/catalog_library.txt

Standard library only, plus ffmpeg on PATH.
"""

import argparse
import hashlib
import os
import shutil
import subprocess
import sys
from pathlib import Path

import gamesdb

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_GAMES = REPO_ROOT / "games.json"

# The card's managed directories, named as include/sd_manager.h names them:
# ROM_PATH_GB, ART_PATH, SHOT_PATH, SAVE_PATH and CATALOG_PATH. A rename there
# should be findable from here.
ROM_DIR = "roms/gb"
ART_DIR = "art"
SHOT_DIR = "shot"
SAVE_DIR = "saves"
CATALOG_NAME = "catalog.txt"

# Pruned when games.json does not name a file in them. SAVE_DIR is deliberately
# absent: the emulator owns it.
MANAGED_DIRS = (ROM_DIR, ART_DIR, SHOT_DIR)

# ART_SUFFIX in include/sd_manager.h.
ART_SUFFIX = ".565"

# 96x96 pixels, two bytes each, no header — the exact size sd_media_read()
# demands, since a file of any other size is from a different imaging run.
ART_EDGE = 96
ART_BYTES = ART_EDGE * ART_EDGE * 2

# The temp suffix, the same one SAVE_TMP_SUFFIX names on the device.
TMP_SUFFIX = ".tmp"

# docs/CATALOG_FORMAT.md § Art, verbatim. Sources are RGBA, so they are flattened
# onto black and letterboxed rather than stretched.
FFMPEG_FILTER = (
    f"scale={ART_EDGE}:{ART_EDGE}:force_original_aspect_ratio=decrease,"
    f"pad={ART_EDGE}:{ART_EDGE}:-1:-1:color=black,format=rgb24"
)


class Item:
    """One file the card is expected to carry, and where it comes from."""

    def __init__(self, relpath, kind, source=None):
        self.relpath = relpath
        self.kind = kind  # "rom" | "art" | "shot" | "catalog"
        self.source = source

    def __repr__(self):
        return f"Item({self.relpath!r}, {self.kind!r})"


def sha256_of(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def sha256_of_bytes(data):
    return hashlib.sha256(data).hexdigest()


def write_atomic(path, data):
    """Write bytes via <path>.tmp then rename, so no reader sees a half file."""
    path = Path(path)
    temp = path.with_name(path.name + TMP_SUFFIX)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(temp, "wb") as handle:
        handle.write(data)
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(temp, path)


def copy_if_changed(source, destination):
    """Copy source over destination unless it is already the same bytes.

    Returns True when it copied. Size is checked before the hash because a
    differing size settles it without reading 300 KB of ROM.
    """
    source = Path(source)
    destination = Path(destination)
    if destination.is_file():
        if destination.stat().st_size == source.stat().st_size:
            if sha256_of(destination) == sha256_of(source):
                return False
    write_atomic(destination, source.read_bytes())
    return True


def ffmpeg_to_565(source):
    """Convert one image to raw RGB565 bytes with the contract's recipe."""
    command = [
        "ffmpeg",
        "-nostdin",
        "-loglevel",
        "error",
        "-y",
        "-i",
        str(source),
        "-vf",
        FFMPEG_FILTER,
        "-f",
        "rawvideo",
        "-pix_fmt",
        "rgb565le",
        "-",
    ]
    result = subprocess.run(command, capture_output=True)
    if result.returncode != 0:
        raise RuntimeError(
            f"ffmpeg failed on {source}: "
            f"{result.stderr.decode('utf-8', 'replace').strip()}"
        )
    if len(result.stdout) != ART_BYTES:
        raise RuntimeError(
            f"ffmpeg produced {len(result.stdout)} bytes for {source}, "
            f"expected {ART_BYTES}"
        )
    return result.stdout


def convert_565(source, destination):
    """Convert source into destination unless it already holds that exact output.

    Returns True when it wrote. The conversion is deterministic, so comparing
    the destination against a fresh conversion is the idempotency check; the
    size is checked first so an obviously wrong file skips the hashing.
    """
    destination = Path(destination)
    data = ffmpeg_to_565(source)
    if destination.is_file() and destination.stat().st_size == ART_BYTES:
        if sha256_of(destination) == sha256_of_bytes(data):
            return False
    write_atomic(destination, data)
    return True


def plan(games, rom_dir, media_dir):
    """Every file the card should carry, in a stable order."""
    items = []
    for game in games:
        stem = gamesdb.stem(game["filename"])
        items.append(
            Item(
                f"{ROM_DIR}/{game['filename']}",
                "rom",
                Path(rom_dir) / game["filename"],
            )
        )
        for field, directory in (("art", ART_DIR), ("shot", SHOT_DIR)):
            relative = game.get(field) or ""
            if relative == "":
                continue
            items.append(
                Item(
                    f"{directory}/{stem}{ART_SUFFIX}",
                    field,
                    Path(media_dir) / relative,
                )
            )
    items.append(Item(CATALOG_NAME, "catalog"))
    return items


def prune(target, expected):
    """Remove files in the managed directories that games.json does not name.

    Only files, only in the managed directories, and never inside /saves.
    """
    target = Path(target)
    keep = {item.relpath for item in expected}
    removed = []
    for directory in MANAGED_DIRS:
        root = target / directory
        if not root.is_dir():
            continue
        for path in sorted(root.rglob("*")):
            if not path.is_file():
                continue
            relative = path.relative_to(target).as_posix()
            if relative in keep:
                continue
            path.unlink()
            removed.append(relative)
    return removed


def verify(target, expected):
    """Re-read every expected file and check it against its source.

    ROMs against the source's hash; art and snapshots against a fresh
    conversion; the catalog against a fresh emission. This is what catches a
    copy that went wrong after it was written.
    """
    target = Path(target)
    problems = []
    for item in expected:
        path = target / item.relpath
        if not path.is_file():
            problems.append(f"missing: {item.relpath}")
            continue
        if item.kind == "rom":
            if sha256_of(path) != sha256_of(item.source):
                problems.append(f"differs from its source: {item.relpath}")
        elif item.kind in ("art", "shot"):
            if path.stat().st_size != ART_BYTES:
                problems.append(
                    f"is {path.stat().st_size} bytes, expected {ART_BYTES}: "
                    f"{item.relpath}"
                )
            elif sha256_of(path) != sha256_of_bytes(ffmpeg_to_565(item.source)):
                problems.append(f"differs from its source: {item.relpath}")
    return problems


def manifest(target, expected):
    """`<sha256>  <size>  <path>` per file, sorted by path.

    No timestamps and no absolute paths, so two runs of the same inputs produce
    byte-identical text and ten cards can be compared to each other.
    """
    target = Path(target)
    lines = []
    for item in sorted(expected, key=lambda entry: entry.relpath):
        path = target / item.relpath
        if not path.is_file():
            continue
        lines.append(f"{sha256_of(path)}  {path.stat().st_size}  {item.relpath}")
    return "\n".join(lines) + "\n"


def parse_args(argv):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--target", help="the mounted card root")
    parser.add_argument("--games", default=str(DEFAULT_GAMES))
    parser.add_argument(
        "--rom-dir",
        default=os.environ.get(gamesdb.ROM_DIR_ENV, ""),
        help=f"the curated ROM directory; defaults to ${gamesdb.ROM_DIR_ENV}",
    )
    parser.add_argument(
        "--media-dir",
        default=os.environ.get(gamesdb.MEDIA_DIR_ENV, ""),
        help=f"the ES-DE media directory; defaults to ${gamesdb.MEDIA_DIR_ENV}",
    )
    parser.add_argument(
        "--catalog-only",
        metavar="PATH",
        help="write just the generated catalog to PATH and exit",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify an existing card and print its manifest, writing nothing",
    )
    parser.add_argument("--manifest", metavar="PATH", help="also write the manifest here")
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)

    try:
        games = gamesdb.load_games(args.games)
    except (OSError, ValueError) as error:
        print(f"cannot read {args.games}: {error}", file=sys.stderr)
        return 1

    # Catalog-only needs neither the card nor the sources: it is the fixture
    # generator, and the catalog is emitted from games.json alone.
    if args.catalog_only:
        problems, _ = gamesdb.validate(games)
        if problems:
            for problem in problems:
                print(f"problem: {problem}", file=sys.stderr)
            return 1
        write_atomic(args.catalog_only, gamesdb.emit_catalog(games).encode("ascii"))
        print(f"wrote {args.catalog_only}", file=sys.stderr)
        return 0

    if not args.target:
        print("no card: pass --target, or --catalog-only to write just the catalog",
              file=sys.stderr)
        return 2
    if args.rom_dir == "":
        print(f"no ROM directory: pass --rom-dir or set ${gamesdb.ROM_DIR_ENV}",
              file=sys.stderr)
        return 2
    if args.media_dir == "":
        print(f"no media directory: pass --media-dir or set ${gamesdb.MEDIA_DIR_ENV}",
              file=sys.stderr)
        return 2

    # Before anything is written: ffmpeg has to exist, or a run would copy 30 MB
    # of ROMs and then fail on the first cover.
    if shutil.which("ffmpeg") is None:
        print("ffmpeg is not on PATH; it converts the art and cannot be skipped",
              file=sys.stderr)
        return 1

    target = Path(args.target)
    if not target.is_dir():
        print(f"no such card directory: {target}", file=sys.stderr)
        return 2

    problems, notices = gamesdb.validate(
        games, rom_dir=Path(args.rom_dir), media_dir=Path(args.media_dir)
    )
    for notice in notices:
        print(f"note: {notice}", file=sys.stderr)
    if problems:
        for problem in problems:
            print(f"problem: {problem}", file=sys.stderr)
        print(f"{len(problems)} problems; nothing was written", file=sys.stderr)
        return 1

    expected = plan(games, args.rom_dir, args.media_dir)

    if args.check:
        failures = verify(target, expected)
    else:
        for directory in (*MANAGED_DIRS, SAVE_DIR):
            (target / directory).mkdir(parents=True, exist_ok=True)

        copied = 0
        converted = 0
        for item in expected:
            if item.kind == "rom":
                copied += copy_if_changed(item.source, target / item.relpath)
            elif item.kind in ("art", "shot"):
                converted += convert_565(item.source, target / item.relpath)

        catalog = gamesdb.emit_catalog(games).encode("ascii")
        wrote_catalog = True
        catalog_path = target / CATALOG_NAME
        if catalog_path.is_file() and catalog_path.read_bytes() == catalog:
            wrote_catalog = False
        else:
            write_atomic(catalog_path, catalog)

        removed = prune(target, expected)
        print(
            f"{len(games)} entries: {copied} ROMs copied, {converted} images "
            f"converted, catalog {'written' if wrote_catalog else 'unchanged'}, "
            f"{len(removed)} strays removed",
            file=sys.stderr,
        )
        for relative in removed:
            print(f"removed: {relative}", file=sys.stderr)
        failures = verify(target, expected)

    text = manifest(target, expected)
    sys.stdout.write(text)
    if args.manifest:
        write_atomic(args.manifest, text.encode("ascii"))

    for failure in failures:
        print(f"failed verify: {failure}", file=sys.stderr)
    if failures:
        print(f"{len(failures)} files did not verify", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
