"""Image an SD card for the cartridge system, idempotently.

Makes the layout docs/CATALOG_FORMAT.md § SD card layout specifies, from
games.json plus the private ROM and ES-DE media directories:

    /roms/gb/<filename>     the ROM, copied byte for byte
    /art/<stem>.565         cover,   96x96 raw RGB565 little-endian, 18432 bytes
    /shot/<stem>.565        snapshot, same format
    /manual/<stem>.2bp      scanned manual, 2 bpp pages in LZ4-compressed bands
    /desc/<stem>.txt        full description, ASCII, blank line between paragraphs
    /saves/                 created empty and never otherwise touched
    /catalog.txt            generated by gamesdb.emit_catalog

Ten cards have to be identical, so the tool is idempotent and it prunes: a file
in a managed directory that games.json does not name is removed, because a card
that still carries last week's ROM is not the same card as a fresh one. /saves
is never pruned and never listed — a kid's save is not a stray.

Every write goes to a temp file and is renamed into place, the same shape
sd_save_state() uses on the device, so a card pulled mid-run never holds a half
file. Nothing is written at all until games.json validates.

Images are converted by ffmpeg with the recipe the contract states, never scaled
in Python: the byte order has to match what the display pushes. Manuals are
rendered page by page by poppler at their stored size, then quantized to four
greys, packed and compressed here.

    CYD_ROM_DIR=... CYD_MEDIA_DIR=... python tools/image_sd.py --target /run/media/me/GB
    python tools/image_sd.py --catalog-only test/fixtures/catalog_library.txt

Standard library only, plus the lz4 package, and ffmpeg and poppler's pdfinfo
and pdftoppm on PATH.
"""

import argparse
import collections
import concurrent.futures
import hashlib
import os
import re
import shutil
import struct
import subprocess
import sys
from pathlib import Path

import gamesdb

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_GAMES = REPO_ROOT / "games.json"

# The card's managed directories, named as include/sd_manager.h names them:
# ROM_PATH_GB, ART_PATH, SHOT_PATH, MANUAL_PATH, DESC_PATH, SAVE_PATH and
# CATALOG_PATH. A
# rename there should be findable from here.
ROM_DIR = "roms/gb"
ART_DIR = "art"
SHOT_DIR = "shot"
MANUAL_DIR = "manual"
DESC_DIR = "desc"
SAVE_DIR = "saves"
CATALOG_NAME = "catalog.txt"

# Pruned when games.json does not name a file in them. SAVE_DIR is deliberately
# absent: the emulator owns it.
MANAGED_DIRS = (ROM_DIR, ART_DIR, SHOT_DIR, MANUAL_DIR, DESC_DIR)

# ART_SUFFIX in include/sd_manager.h.
ART_SUFFIX = ".565"

# 96x96 pixels, two bytes each, no header — the exact size sd_media_read()
# demands, since a file of any other size is from a different imaging run.
ART_EDGE = 96
ART_BYTES = ART_EDGE * ART_EDGE * 2

# docs/CATALOG_FORMAT.md § Manuals: /manual/<stem>.2bp, one file per game, an
# 8-byte header of magic, u16 version and u16 page count, then a u16 width and
# u16 height per page, then every page's table of u32 band offsets, then the
# LZ4 blocks back to back, little-endian. Each band is MANUAL_BAND_ROWS rows of
# 2 bpp pixels, compressed on its own so the reader can decode any one band.
# MANUAL_SUFFIX in include/sd_manager.h; the magic, version and band height are
# lib/gbcore/ui/manual.h's.
MANUAL_SUFFIX = ".2bp"
MANUAL_MAGIC = b"GBMN"
MANUAL_VERSION = 2
MANUAL_BAND_ROWS = 16

# DESC_SUFFIX in include/sd_manager.h. The file is the description's bytes
# exactly, with no trailing newline: the firmware reads it whole and shows it.
DESC_SUFFIX = ".txt"

# Every stored page fits within twice the game window, so one tile of it is one
# window. A page wider than 2:1 is a spread and is stored as its two halves.
PAGE_BOX = (532, 480)
SPREAD_ASPECT = 2.0

# The temp suffix, the same one SAVE_TMP_SUFFIX names on the device.
TMP_SUFFIX = ".tmp"

# docs/CATALOG_FORMAT.md § Art, verbatim. Sources are RGBA, so they are flattened
# onto black and letterboxed rather than stretched.
FFMPEG_FILTER = (
    f"scale={ART_EDGE}:{ART_EDGE}:force_original_aspect_ratio=decrease,"
    f"pad={ART_EDGE}:{ART_EDGE}:-1:-1:color=black,format=rgb24"
)


class Item:
    """One file the card is expected to carry, and where it comes from."""

    def __init__(self, relpath, kind, source=None):
        self.relpath = relpath
        self.kind = kind  # "rom" | "art" | "shot" | "manual" | "desc" | "catalog"
        # A Path to copy or convert from; for "desc", the text itself.
        self.source = source

    def __repr__(self):
        return f"Item({self.relpath!r}, {self.kind!r})"


def sha256_of(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def sha256_of_bytes(data):
    return hashlib.sha256(data).hexdigest()


def write_atomic(path, data):
    """Write bytes via <path>.tmp then rename, so no reader sees a half file."""
    path = Path(path)
    temp = path.with_name(path.name + TMP_SUFFIX)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(temp, "wb") as handle:
        handle.write(data)
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(temp, path)


def copy_if_changed(source, destination):
    """Copy source over destination unless it is already the same bytes.

    Returns True when it copied. Size is checked before the hash because a
    differing size settles it without reading 300 KB of ROM.
    """
    source = Path(source)
    destination = Path(destination)
    if destination.is_file():
        if destination.stat().st_size == source.stat().st_size:
            if sha256_of(destination) == sha256_of(source):
                return False
    write_atomic(destination, source.read_bytes())
    return True


def ffmpeg_to_565(source):
    """Convert one image to raw RGB565 bytes with the contract's recipe."""
    command = [
        "ffmpeg",
        "-nostdin",
        "-loglevel",
        "error",
        "-y",
        "-i",
        str(source),
        "-vf",
        FFMPEG_FILTER,
        "-f",
        "rawvideo",
        "-pix_fmt",
        "rgb565le",
        "-",
    ]
    result = subprocess.run(command, capture_output=True)
    if result.returncode != 0:
        raise RuntimeError(
            f"ffmpeg failed on {source}: "
            f"{result.stderr.decode('utf-8', 'replace').strip()}"
        )
    if len(result.stdout) != ART_BYTES:
        raise RuntimeError(
            f"ffmpeg produced {len(result.stdout)} bytes for {source}, "
            f"expected {ART_BYTES}"
        )
    return result.stdout


def convert_565(source, destination):
    """Convert source into destination unless it already holds that exact output.

    Returns True when it wrote. The conversion is deterministic, so comparing
    the destination against a fresh conversion is the idempotency check; the
    size is checked first so an obviously wrong file skips the hashing.
    """
    return write_if_changed(destination, ffmpeg_to_565(source))


def fit_within(aspect):
    """The largest integer (w, h) of this width-to-height aspect inside PAGE_BOX."""
    box_w, box_h = PAGE_BOX
    if aspect >= box_w / box_h:
        return box_w, max(1, round(box_w / aspect))
    return max(1, round(box_h * aspect)), box_h


def page_outputs(w_pts, h_pts):
    """The stored pages one source page becomes, as (w, h, scale, half) specs.

    scale is output pixels per point of the part rendered. half is None for a
    whole page, else 0 for the left half of a spread and 1 for the right: a page
    wider than SPREAD_ASPECT is cut down the middle and each half is fitted on
    its own aspect, because a spread fitted whole leaves each page unreadable.
    """
    if w_pts / h_pts <= SPREAD_ASPECT:
        w, h = fit_within(w_pts / h_pts)
        return [(w, h, w / w_pts, None)]
    half_pts = w_pts / 2
    w, h = fit_within(half_pts / h_pts)
    return [(w, h, w / half_pts, half) for half in (0, 1)]


def quantize_page(grey, w, h):
    """The 256-entry table from grey level to 2 bpp level, for this page.

    Paper is the most common grey from 128 up and becomes 0, white; ink is the
    1st percentile and becomes 3, black; the greys between are spaced evenly
    and rounded. Paper and ink are kept at least 8 levels apart, so a page of
    one grey still quantizes cleanly. Searching for paper only in the light
    half means a dark page's light box stays white rather than inverting.
    """
    counts = collections.Counter(grey)
    histogram = [counts[level] for level in range(256)]
    paper = 128
    for level in range(128, 256):
        if histogram[level] > histogram[paper]:
            paper = level
    # The 1st percentile: the level of the ((n - 1) / 100)th darkest pixel.
    rank = (w * h - 1) // 100
    ink = 0
    below = 0
    for level in range(256):
        below += histogram[level]
        if below > rank:
            ink = level
            break
    if paper - ink < 8:
        ink = max(0, paper - 8)
    table = []
    for level in range(256):
        lightness = round(3 * (level - ink) / (paper - ink))
        table.append(3 - min(3, max(0, lightness)))
    return bytes(table)


def pack_page_2bpp(grey, w, h, table):
    """One page's raster: rows MSB-first at 2 bpp, 0 white to 3 black, rows
    byte-padded with zero bits.

    Pixels are mapped to ASCII '0'-'3' by a translate table and each row is
    parsed as a base-4 integer, so no Python loop touches a single pixel.
    """
    digits = grey.translate(bytes(0x30 + level for level in table))
    row_bytes = (w + 3) // 4
    padding = b"0" * (row_bytes * 4 - w)
    rows = []
    for y in range(h):
        row = digits[y * w:(y + 1) * w] + padding
        rows.append(int(row, 4).to_bytes(row_bytes, "big"))
    return b"".join(rows)


def encode_manual(pages):
    """The whole .2bp file from a list of (w, h, raster).

    A raster of the wrong length is refused here, because the reader refuses a
    band that does not decode to exactly its rows.
    """
    import lz4.block

    header = struct.pack("<4sHH", MANUAL_MAGIC, MANUAL_VERSION, len(pages))
    sizes = []
    blocks = []
    for w, h, raster in pages:
        row_bytes = (w + 3) // 4
        if len(raster) != row_bytes * h:
            raise ValueError(
                f"a {w}x{h} page needs {row_bytes * h} bytes, not {len(raster)}"
            )
        sizes.append(struct.pack("<HH", w, h))
        band_bytes = MANUAL_BAND_ROWS * row_bytes
        blocks.append([
            lz4.block.compress(
                raster[start:start + band_bytes],
                mode="high_compression",
                compression=12,
                store_size=False,
            )
            for start in range(0, len(raster), band_bytes)
        ])
    # Every offset is absolute, so the blocks start after all the tables.
    offset = len(header) + 4 * len(pages) + sum(4 * (len(page) + 1) for page in blocks)
    tables = []
    for page in blocks:
        offsets = [offset]
        for block in page:
            offset += len(block)
            offsets.append(offset)
        tables.append(struct.pack(f"<{len(offsets)}I", *offsets))
    return (
        header
        + b"".join(sizes)
        + b"".join(tables)
        + b"".join(block for page in blocks for block in page)
    )


# One "Page    N size:  W x H pts" and one "Page    N rot:  R" line per page.
PDFINFO_PAGE = re.compile(r"^Page\s+(\d+)\s+(size|rot):\s+(\S+)(?:\s+x\s+(\S+))?", re.M)


# pdftoppm -gray writes 8-bit PGM.
PGM_HEADER = re.compile(rb"P5\s+(\d+)\s+(\d+)\s+255\s")


def pdf_page_sizes(source):
    """Each page's (width, height) in points as it is displayed, rotation applied."""
    result = subprocess.run(
        ["pdfinfo", "-f", "1", "-l", "99999", str(source)],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"pdfinfo failed on {source}: {result.stderr.strip()}")
    sizes = {}
    rotations = {}
    for page, field, first, second in PDFINFO_PAGE.findall(result.stdout):
        if field == "size":
            sizes[int(page)] = (float(first), float(second))
        else:
            rotations[int(page)] = int(first) % 180
    pages = []
    for page in sorted(sizes):
        w_pts, h_pts = sizes[page]
        if rotations.get(page, 0) == 90:
            w_pts, h_pts = h_pts, w_pts
        pages.append((w_pts, h_pts))
    return pages


def pdftoppm_grey(source, page, w, h, half):
    """One page rendered to 8-bit grey at w x h, or one half of it at w x h."""
    command = ["pdftoppm", "-gray", "-f", str(page), "-l", str(page)]
    if half is None:
        command += ["-scale-to-x", str(w), "-scale-to-y", str(h)]
    else:
        command += [
            "-scale-to-x", str(2 * w), "-scale-to-y", str(h),
            "-x", str(half * w), "-y", "0", "-W", str(w), "-H", str(h),
        ]
    result = subprocess.run(command + [str(source)], capture_output=True)
    if result.returncode != 0:
        raise RuntimeError(
            f"pdftoppm failed on {source} page {page}: "
            f"{result.stderr.decode(errors='replace').strip()}"
        )
    # A binary PGM: "P5", width, height and maxval, then exactly one whitespace
    # byte before the pixels — which may themselves start with whitespace values.
    header = PGM_HEADER.match(result.stdout)
    if header is None or (int(header[1]), int(header[2])) != (w, h):
        raise RuntimeError(f"pdftoppm gave no {w}x{h} PGM for page {page} of {source}")
    grey = result.stdout[header.end():header.end() + w * h]
    if len(grey) != w * h:
        raise RuntimeError(f"pdftoppm gave a short page {page} of {source}")
    return grey


def render_manual(source):
    """The whole .2bp for one PDF: every page fitted, split and quantized."""
    pages = []
    for number, (w_pts, h_pts) in enumerate(pdf_page_sizes(source), start=1):
        for w, h, _, half in page_outputs(w_pts, h_pts):
            grey = pdftoppm_grey(source, number, w, h, half)
            table = quantize_page(grey, w, h)
            pages.append((w, h, pack_page_2bpp(grey, w, h, table)))
    return encode_manual(pages)


def render_manuals(items):
    """{relpath: .2bp bytes} for the manual items, one manual per process."""
    manuals = [item for item in items if item.kind == "manual"]
    if not manuals:
        return {}
    with concurrent.futures.ProcessPoolExecutor() as pool:
        rendered = pool.map(render_manual, [item.source for item in manuals])
        return {item.relpath: data for item, data in zip(manuals, rendered)}


def write_if_changed(destination, data):
    """Write data unless destination already holds exactly it. True when it wrote."""
    destination = Path(destination)
    if destination.is_file() and destination.stat().st_size == len(data):
        if sha256_of(destination) == sha256_of_bytes(data):
            return False
    write_atomic(destination, data)
    return True


def plan(games, rom_dir, media_dir):
    """Every file the card should carry, in a stable order."""
    items = []
    for game in games:
        stem = gamesdb.stem(game["filename"])
        items.append(
            Item(
                f"{ROM_DIR}/{game['filename']}",
                "rom",
                Path(rom_dir) / game["filename"],
            )
        )
        for field, directory in (("art", ART_DIR), ("shot", SHOT_DIR)):
            relative = game.get(field) or ""
            if relative == "":
                continue
            items.append(
                Item(
                    f"{directory}/{stem}{ART_SUFFIX}",
                    field,
                    Path(media_dir) / relative,
                )
            )
        if game.get("manual"):
            items.append(
                Item(
                    f"{MANUAL_DIR}/{stem}{MANUAL_SUFFIX}",
                    "manual",
                    Path(media_dir) / game["manual"],
                )
            )
        if game["description"]:
            items.append(
                Item(
                    f"{DESC_DIR}/{stem}{DESC_SUFFIX}",
                    "desc",
                    game["description"],
                )
            )
    items.append(Item(CATALOG_NAME, "catalog"))
    return items


def prune(target, expected):
    """Remove files in the managed directories that games.json does not name.

    Only files, only in the managed directories, and never inside /saves.
    """
    target = Path(target)
    keep = {item.relpath for item in expected}
    removed = []
    for directory in MANAGED_DIRS:
        root = target / directory
        if not root.is_dir():
            continue
        for path in sorted(root.rglob("*")):
            if not path.is_file():
                continue
            relative = path.relative_to(target).as_posix()
            if relative in keep:
                continue
            path.unlink()
            removed.append(relative)
    return removed


def verify(target, expected, rendered=None):
    """Re-read every expected file and check it against its source.

    ROMs against the source's hash; art and snapshots against a fresh
    conversion; manuals against a fresh render, or against `rendered` when the
    caller has just made one; descriptions against games.json's text; the
    catalog against a fresh emission. This is
    what catches a copy that went wrong after it was written.
    """
    target = Path(target)
    problems = []
    if rendered is None:
        rendered = render_manuals(
            [item for item in expected if (target / item.relpath).is_file()]
        )
    for item in expected:
        path = target / item.relpath
        if not path.is_file():
            problems.append(f"missing: {item.relpath}")
            continue
        if item.kind == "rom":
            if sha256_of(path) != sha256_of(item.source):
                problems.append(f"differs from its source: {item.relpath}")
        elif item.kind in ("art", "shot"):
            if path.stat().st_size != ART_BYTES:
                problems.append(
                    f"is {path.stat().st_size} bytes, expected {ART_BYTES}: "
                    f"{item.relpath}"
                )
            elif sha256_of(path) != sha256_of_bytes(ffmpeg_to_565(item.source)):
                problems.append(f"differs from its source: {item.relpath}")
        elif item.kind == "manual":
            if sha256_of(path) != sha256_of_bytes(rendered[item.relpath]):
                problems.append(f"differs from its source: {item.relpath}")
        elif item.kind == "desc":
            if path.read_bytes() != item.source.encode("ascii"):
                problems.append(f"differs from its source: {item.relpath}")
    return problems


def manifest(target, expected):
    """`<sha256>  <size>  <path>` per file, sorted by path.

    No timestamps and no absolute paths, so two runs of the same inputs produce
    byte-identical text and ten cards can be compared to each other.
    """
    target = Path(target)
    lines = []
    for item in sorted(expected, key=lambda entry: entry.relpath):
        path = target / item.relpath
        if not path.is_file():
            continue
        lines.append(f"{sha256_of(path)}  {path.stat().st_size}  {item.relpath}")
    return "\n".join(lines) + "\n"


def parse_args(argv):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--target", help="the mounted card root")
    parser.add_argument("--games", default=str(DEFAULT_GAMES))
    parser.add_argument(
        "--rom-dir",
        default=os.environ.get(gamesdb.ROM_DIR_ENV, ""),
        help=f"the curated ROM directory; defaults to ${gamesdb.ROM_DIR_ENV}",
    )
    parser.add_argument(
        "--media-dir",
        default=os.environ.get(gamesdb.MEDIA_DIR_ENV, ""),
        help=f"the ES-DE media directory; defaults to ${gamesdb.MEDIA_DIR_ENV}",
    )
    parser.add_argument(
        "--catalog-only",
        metavar="PATH",
        help="write just the generated catalog to PATH and exit",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify an existing card and print its manifest, writing nothing",
    )
    parser.add_argument("--manifest", metavar="PATH", help="also write the manifest here")
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)

    try:
        games = gamesdb.load_games(args.games)
    except (OSError, ValueError) as error:
        print(f"cannot read {args.games}: {error}", file=sys.stderr)
        return 1

    # Catalog-only needs neither the card nor the sources: it is the fixture
    # generator, and the catalog is emitted from games.json alone.
    if args.catalog_only:
        problems, _ = gamesdb.validate(games)
        if problems:
            for problem in problems:
                print(f"problem: {problem}", file=sys.stderr)
            return 1
        write_atomic(args.catalog_only, gamesdb.emit_catalog(games).encode("ascii"))
        print(f"wrote {args.catalog_only}", file=sys.stderr)
        return 0

    if not args.target:
        print("no card: pass --target, or --catalog-only to write just the catalog",
              file=sys.stderr)
        return 2
    if args.rom_dir == "":
        print(f"no ROM directory: pass --rom-dir or set ${gamesdb.ROM_DIR_ENV}",
              file=sys.stderr)
        return 2
    if args.media_dir == "":
        print(f"no media directory: pass --media-dir or set ${gamesdb.MEDIA_DIR_ENV}",
              file=sys.stderr)
        return 2

    # Before anything is written: ffmpeg has to exist, or a run would copy 30 MB
    # of ROMs and then fail on the first cover.
    if shutil.which("ffmpeg") is None:
        print("ffmpeg is not on PATH; it converts the art and cannot be skipped",
              file=sys.stderr)
        return 1
    # Likewise poppler, but only a library with a manual needs it.
    if any(game.get("manual") for game in games if isinstance(game, dict)):
        for tool in ("pdfinfo", "pdftoppm"):
            if shutil.which(tool) is None:
                print(f"{tool} is not on PATH; poppler renders the manuals and "
                      f"cannot be skipped", file=sys.stderr)
                return 1
        try:
            import lz4.block  # noqa: F401
        except ImportError:
            print("the lz4 package is not installed; it compresses the manuals "
                  "and cannot be skipped", file=sys.stderr)
            return 1

    target = Path(args.target)
    if not target.is_dir():
        print(f"no such card directory: {target}", file=sys.stderr)
        return 2

    problems, notices = gamesdb.validate(
        games, rom_dir=Path(args.rom_dir), media_dir=Path(args.media_dir)
    )
    for notice in notices:
        print(f"note: {notice}", file=sys.stderr)
    if problems:
        for problem in problems:
            print(f"problem: {problem}", file=sys.stderr)
        print(f"{len(problems)} problems; nothing was written", file=sys.stderr)
        return 1

    expected = plan(games, args.rom_dir, args.media_dir)

    if args.check:
        failures = verify(target, expected)
    else:
        for directory in (*MANAGED_DIRS, SAVE_DIR):
            (target / directory).mkdir(parents=True, exist_ok=True)

        # Strays go first: games.json does not name them, so nothing is lost,
        # and a card still full of an old format's files has room for the new.
        removed = prune(target, expected)

        copied = 0
        converted = 0
        rendered = render_manuals(expected)
        manuals = 0
        descriptions = 0
        for item in expected:
            if item.kind == "rom":
                copied += copy_if_changed(item.source, target / item.relpath)
            elif item.kind in ("art", "shot"):
                converted += convert_565(item.source, target / item.relpath)
            elif item.kind == "manual":
                manuals += write_if_changed(
                    target / item.relpath, rendered[item.relpath]
                )
            elif item.kind == "desc":
                descriptions += write_if_changed(
                    target / item.relpath, item.source.encode("ascii")
                )

        catalog = gamesdb.emit_catalog(games).encode("ascii")
        wrote_catalog = True
        catalog_path = target / CATALOG_NAME
        if catalog_path.is_file() and catalog_path.read_bytes() == catalog:
            wrote_catalog = False
        else:
            write_atomic(catalog_path, catalog)

        print(
            f"{len(games)} entries: {copied} ROMs copied, {converted} images "
            f"converted, {manuals} manuals written, "
            f"{descriptions} descriptions written, "
            f"catalog {'written' if wrote_catalog else 'unchanged'}, "
            f"{len(removed)} strays removed",
            file=sys.stderr,
        )
        for relative in removed:
            print(f"removed: {relative}", file=sys.stderr)
        failures = verify(target, expected, rendered)

    text = manifest(target, expected)
    sys.stdout.write(text)
    if args.manifest:
        write_atomic(args.manifest, text.encode("ascii"))

    for failure in failures:
        print(f"failed verify: {failure}", file=sys.stderr)
    if failures:
        print(f"{len(failures)} files did not verify", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
